environment: test

pullPolicy: IfNotPresent

rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1

app:
  name: polls
  frontend:
    imageRepository: frontend
    imageTag: v2
    replicaCount: 1
    resources:
      limits:
        cpu: 1
        memory: "300Mi"
  backend:
    imageRepository: backend
    imageTag: v2
    replicaCount: 1
    resources:
      limits:
        cpu: 1
        memory: "500Mi"
  init:
    imageRepository: busybox
    imageTag: 1.28

database:
  mysql:
    serviceName: mysql-database
    replicaCount: 1
    imageRepository: mysql
    imageTag: 5.6
    storageName: mysql-persistent-storage
    storageAmmount: 500Mi
    dbName: polls
    resources:
      limits:
        cpu: 1
        memory: "500Mi"

service:
  database:
    internalPort: 3306
    externalPort: 3306
  frontend:
    internalPort: 80
    externalPort: 80
  backend:
    internalPort: 8080
    externalPort: 8080

#Base64 encoded value. Use command base64 for encoding/decoding secrets.
#For encoding: echo -n 'textplain-secret' | base64
#For decoding: echo 'base64-secret' | base64 -d
secret:
  database:
    mysql:
      rootPassword: Y2hhbmdlbWU=
      userUsername: Y2hhbmdlbWU=
      userPassword: Y2hhbmdlbWU=
