environment: test

pullPolicy: IfNotPresent

rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1

app:
  name: polls
  dnsName: app.polls.com
  frontend:
    imageRepository: guilleguerrero/polls-frontend
    imageTag: 1.0.0
    replicaCount: 1
    resources:
      limits:
        cpu: 0.5
        memory: "700Mi"
      requests:
        cpu: 0.5
        memory: "300Mi"
    autoscaling:
      maxReplicas: 2
      cpuAveragePercentageUtilization: 60
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
  backend:
    imageRepository: guilleguerrero/polls-backend
    imageTag: 1.0.0
    replicaCount: 1
    resources:
      limits:
        cpu: 0.5
        memory: "1000Mi"
      requests:
        cpu: 0.5
        memory: "500Mi"
    autoscaling:
      maxReplicas: 2
      cpuAveragePercentageUtilization: 60
    livenessProbe:
      initialDelaySeconds: 250
      periodSeconds: 10
    readinessProbe:
      initialDelaySeconds: 300
      periodSeconds: 10
  init:
    busybox:
      imageRepository: busybox
      imageTag: 1.28
    curl:
      imageRepository: curlimages/curl
      imageTag: 8.4.0

database:
  mysql:
    serviceName: mysql-database
    replicaCount: 1
    imageRepository: mysql
    imageTag: 5.6
    storageName: mysql-persistent-storage
    storageAmmount: 500Mi
    dbName: polls
    resources:
      limits:
        cpu: 0.5
        memory: "1000Mi"
      requests:
        cpu: 0.5
        memory: "500Mi"

service:
  database:
    internalPort: 3306
    externalPort: 3306
  frontend:
    internalPort: 80
    externalPort: 80
  backend:
    internalPort: 8080
    externalPort: 8080

monitoring:
  enabled: false
  dnsName: kibana.polls.com
  elasticVersion: 8.11.1

#Base64 encoded value. Use command base64 for encoding/decoding secrets.
#For encoding: echo -n <textplain-secret> | base64
#For decoding: echo <base64-secret> | base64 -d
secret:
  database:
    mysql:
      rootPassword: Y2hhbmdlbWU=
      userUsername: Y2hhbmdlbWU=
      userPassword: Y2hhbmdlbWU=

#Chart dependencies values
metrics-server:
  args:
    - "--kubelet-insecure-tls" #This is necessary so that the certificates are not verified in case docker desktop is used

ingress-nginx:
  controller:
    podAnnotations:
      co.elastic.logs/module: nginx
      co.elastic.logs/fileset.stdout: access
      co.elastic.logs/fileset.stderr: error

eck-operator:
  installCRDs: false
