apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-database-root
  labels:
    release-name: {{ .Release.Name }}
    release-namespace: {{ .Release.Namespace }}
    environment: {{ .Values.environment }}
    app: {{ .Values.app.name }}
type: Opaque
data:
  password: {{ .Values.secret.database.mysql.rootPassword }}
