apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-database-user
  labels:
    release-name: {{ .Release.Name }}
    release-namespace: {{ .Release.Namespace }}
    environment: {{ .Values.environment }}
    app: polls
type: Opaque
data:
  username: {{ .Values.secret.database.mysql.userUsername }}
  password: {{ .Values.secret.database.mysql.userPassword }}
