apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-database
  labels:
    release-name: {{ .Release.Name }}
    release-namespace: {{ .Release.Namespace }}
data:
  name: {{ .Values.config.database.name }}