apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mysql-database
  labels:
    release-name: {{ .Release.Name }}
    release-namespace: {{ .Release.Namespace }}
    environment: {{ .Values.environment }}
    app: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      role: database
      app: {{ .Values.app.name }}
      release: {{ .Release.Name }}
  serviceName: {{ .Values.database.mysql.serviceName }}
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        role: database
        app: {{ .Values.app.name }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:{{ .Values.database.mysql.imageTag }}
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mysql-database-root
                key: password
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mysql-database-user
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mysql-database-user
                key: password
          - name: MYSQL_DATABASE
            value: {{ .Values.database.mysql.dbName }}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
        livenessProbe:
          exec:
            command:
              - bash 
              - "-c"
              - |
                mysqladmin --user root -p${MYSQL_ROOT_PASSWORD} ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - bash 
              - "-c" 
              - | 
                mysql --user root -p${MYSQL_ROOT_PASSWORD} --execute 'SELECT 1' --database ${MYSQL_DATABASE} --host 127.0.0.1
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources:
{{ toYaml .Values.database.mysql.resources | indent 12 }}
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Release.Name }}-local-storage
      resources:
        requests:
          storage: {{ .Values.database.mysql.storageAmmount }}