apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-react-frontend
  labels:
    release-name: {{ .Release.Name }}
    release-namespace: {{ .Release.Namespace }}
    environment: {{ .Values.environment }}
    app: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      role: frontend
      app: {{ .Values.app.name }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
  replicas: {{ .Values.app.frontend.replicaCount }}
  template:
    metadata:
      labels:
        role: frontend
        app: {{ .Values.app.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: react-frontend
          image: {{ .Values.app.frontend.imageRepository}}:{{ .Values.app.frontend.imageTag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.frontend.internalPort }}
          resources:
{{ toYaml .Values.app.frontend.resources | indent 12 }}
          env:
            - name: NODE_APP_URL
              value: http://{{ .Release.Name }}-springboot-backend:{{ .Values.service.backend.internalPort }}/api