apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-react-frontend
  labels:
    release-name: {{ .Release.Name }}
    release-namespace: {{ .Release.Namespace }}
    environment: {{ .Values.environment }}
    app: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      role: frontend
      app: {{ .Values.app.name }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
  replicas: {{ .Values.app.frontend.replicaCount }}
  template:
    metadata:
      labels:
        role: frontend
        app: {{ .Values.app.name }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
        - name: init-rect-frontent
          image: {{ .Values.app.init.busybox.imageRepository}}:{{ .Values.app.init.busybox.imageTag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: ['sh', '-c', "until nslookup {{ .Release.Name }}-springboot-backend; do echo waiting for backend service; sleep 2; done"]
      containers:
        - name: react-frontend
          image: {{ .Values.app.frontend.imageRepository}}:{{ .Values.app.frontend.imageTag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.frontend.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.frontend.internalPort }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.app.frontend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.frontend.livenessProbe.periodSeconds }}
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.frontend.internalPort }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.app.frontend.readinessProbe.initialDelaySeconds}}
            periodSeconds: {{ .Values.app.frontend.readinessProbe.periodSeconds }}
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
{{ toYaml .Values.app.frontend.resources | indent 12 }}
          env:
            - name: NODE_APP_URL
              value: http://{{ .Release.Name }}-springboot-backend:{{ .Values.service.backend.internalPort }}/api