apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-springboot-backend
  labels:
    release-name: {{ .Release.Name }}
    release-namespace: {{ .Release.Namespace }}
    environment: {{ .Values.environment }}
    app: {{ .Values.app.name }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.backend.externalPort }}
    targetPort: 8080
  type: ClusterIP
  clusterIP: None
  selector:
    role: backend
    app: {{ .Values.app.name }}
    release: {{ .Release.Name }}
