apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-react-frontend
  labels:
    release-name: {{ .Release.Name }}
    release-namespace: {{ .Release.Namespace }}
    environment: {{ .Values.environment }}
    app: {{ .Values.app.name }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.frontend.externalPort }}
    targetPort: 80
  type: ClusterIP
  clusterIP: None
  selector:
    role: frontend
    app: {{ .Values.app.name }}
    release: {{ .Release.Name }}
