{{ if .Values.monitoring.enabled }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Release.Name }}-elasticsearch
  labels:
    release-name: {{ .Release.Name }}
    release-namespace: {{ .Release.Namespace }}
    environment: {{ .Values.environment }}
    app: {{ .Values.app.name }}
spec:
  version: {{ .Values.monitoring.elasticVersion }}
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
{{ end }}