{{ if .Values.monitoring.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-kibana-ingress
  labels:
    release-name: {{ .Release.Name }}
    release-namespace: {{ .Release.Namespace }}
    environment: {{ .Values.environment }}
    app: {{ .Values.app.name }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.monitoring.dnsName }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-kibana-kb-http
                port:
                  number: 5601
          - path: /intake
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-apm-apm-http
                port:
                  number: 8200
{{ end }}